### PR TITLE
Lookup table

### PR DESCRIPTION
**Pull request by utkarsh-1905**
@nimishmedatwal issues #24 and #5 are being fixed with this pull request. Review and find bugs, please

### CODE REVIEW

**Review by nimishmedatwal — CHANGES_REQUESTED** [review]
In Electives only the first elective is getting subject name.
image

**Review by nimishmedatwal — CHANGES_REQUESTED** [review]
`L` getting mixed with Course name for some courses.
image

**Review by nimishmedatwal — CHANGES_REQUESTED** [review]
If we could just merge the cells instead of saying Lab Continue, I think it would look better.
image

**Comment by utkarsh-1905** [comment]
> If we could just merge the cells instead of saying Lab Continue, I think it would look better. image

would need to change the basic structure of the table on highly conditional logic

**Comment by utkarsh-1905** [comment]
@nimishmedatwal updated logic to show all subject name, but need some UI changes to display names in good looking manner

**Pull request merged**
