### PR TITLE
Just updated the new timetable excel File as communicated by college timetable has some changes. Also PG timetable is also added to the list. :)

### PR DESCRIPTION
**Pull request by madhavkapila**

### CODE REVIEW

**Comment by madhavkapila** [comment]
The new timetable as communicated by authorities is updated. Also PG timetable is added to list. @utkarsh-1905 sir what a helpful, accessible website you created :) Thank you.

**Comment by madhavkapila** [comment]
@utkarsh-1905 sir I am again getting restyler error. I locally tried increasing docker memory to 1024m also but don't want to commit until I know it will help or not

**Comment by utkarsh-1905** [comment]
Hey, ignore restyled errors, can you verify that time table is correct by randomly opening some classes, also does it contain the iep time table like for 2UoQ

**Comment by madhavkapila** [comment]
> Hey, ignore restyled errors, can you verify that time table is correct by randomly opening some classes, also does it contain the iep time table like for 2UoQ
Screenshot from 2024-08-03 19-53-55
Screenshot from 2024-08-03 19-55-04
Screenshot from 2024-08-03 19-55-48



Yes sir it containes IEP groups and also new PG sheet in it.  I have attached screenshots for reference.

**Comment by utkarsh-1905** [comment]
lgtm

**Comment by madhavkapila** [comment]
@utkarsh-1905 Sir now I viewed live timetable on website it does not have updates. Though the local one is still showing changes. Can you tell why it is happening? Please guide or it takes time to get timetable updated on live server which I think is not possible.

**Comment by utkarsh-1905** [comment]
Hey, it is deployed on my server, and I need to run a script to deploy the latest version, I'll do it tomorrow.

However, if a deployment pipeline was in place this can happen automatically, it would be great if someone creates that

**Comment by utkarsh-1905** [comment]
@madhavkapila deployed, raise a pr to add your name in the readme

**Comment by utkarsh-1905** [comment]
good work

**Comment by madhavkapila** [comment]
> good work


Thanks @utkarsh-1905  Sir your guidance during start of this in previous sem motivated me to contribute somewhat I know to the project. Though now completely focussing on DSA and CP, trying to learn dev also side by side but will dedicatedly do that after DSA is completed.

**Comment by madhavkapila** [comment]
> @madhavkapila deployed, raise a pr to add your name in the readme

If you not mind please allow me to do that during evening

**Comment by madhavkapila** [comment]
> > @madhavkapila deployed, raise a pr to add your name in the readme
> 
> If you not mind please allow me to do that during evening

@utkarsh-1905 Sir updated Readme and created PR #60 .Thanks for such a motivating gesture :).

**Pull request merged**
