### PR TITLE
update timetable :)

### PR DESCRIPTION
**Pull request by MankiratSingh1315**

### CODE REVIEW

**Comment by utkarsh-1905** [comment]
@MankiratSingh1315 looks good, don't merge on main please, create a branch <year-semester> and a raise a pr to that

**Comment by MankiratSingh1315** [comment]
I don't have permissions to create new branch, should I create a PR on [deploy](https://github.com/utkarsh-1905/time-table/tree/deploy) branch?

**Comment by utkarsh-1905** [comment]
Here you go, created a new branch

**Comment by MankiratSingh1315** [comment]
I changed the base branch👍

**Comment by utkarsh-1905** [comment]
thanks

**Pull request merged**
